ARG DEV_IMAGE=dmetasoul/metaspore-dev:v1.0.0
FROM ${DEV_IMAGE} AS build_serving
ARG ENABLE_GPU=OFF

COPY . /opt/metaspore-src

RUN cmake -B /opt/metaspore-build-release -S /opt/metaspore-src -DCMAKE_INSTALL_PREFIX=/opt/metaspore-serving \
    -DCMAKE_PREFIX_PATH="/opt/vcpkg_installed/arm64-linux;/usr/local/cuda" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DENABLE_TESTS=ON -DBUILD_SERVING_BIN=ON -DBUILD_TRAIN_PKG=OFF -DENABLE_GPU=${ENABLE_GPU}
RUN cmake --build /opt/metaspore-build-release --target install -- -j2
RUN mkdir -p /opt/metaspore/debug
RUN objcopy --only-keep-debug /opt/metaspore-serving/bin/metaspore-serving-bin /opt/metaspore/debug/metaspore-serving-bin.debug
RUN objcopy --strip-debug --add-gnu-debuglink=/opt/metaspore/debug/metaspore-serving-bin.debug /opt/metaspore-serving/bin/metaspore-serving-bin /opt/metaspore-serving/bin/metaspore-serving-bin
